version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    environment:
      - NODE_ENV=production
      - HASS_HOST=${HASS_HOST:-http://192.168.3.148:8123}
      - HASS_TOKEN=${HASS_TOKEN}
      - PORT=${PORT:-4000}
      - HASS_SOCKET_URL=${HASS_SOCKET_URL:-ws://192.168.3.148:8123/api/websocket}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    env_file:
      - .env
    restart: unless-stopped